Document: webkit
Title: Debian webkit Manual
Author: <insert document author here>
Abstract: This manual describes what webkit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/webkit/webkit.sgml.gz

Format: postscript
Files: /usr/share/doc/webkit/webkit.ps.gz

Format: text
Files: /usr/share/doc/webkit/webkit.text.gz

Format: HTML
Index: /usr/share/doc/webkit/html/index.html
Files: /usr/share/doc/webkit/html/*.html
